version: "3"

services:
  webserver:
    build:
      # Possible values: php54, php56, php71, php72, php73, php74
      context: ./.bin/php74
    container_name: 'lamp-php74'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links:
      - database
    volumes:
      - ./:/var/www
      - ./public:/var/www/html
      - ./.config/php/php.ini:/usr/local/etc/php/php.ini
      - ./.config/vhosts:/etc/apache2/sites-enabled
      - ./.logs/apache2:/var/log/apache2
    environment:
      PMA_PORT: 8080

  database:
    build:
      # Possible values: mariadb, mysql, mysql8
      context: "./.bin/mysql"
    container_name: 'lamp-database'
    restart: 'always'
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./.logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'lamp-phpmyadmin'
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: docker
      PMA_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - '8080:80'
    volumes:
      - /sessions
      - ./.config/php/php.ini:/usr/local/etc/php/conf.ddock/php-phpmyadmin.ini
